#!/bin/sh

#Параметры------------
REPOPATH="$HOME/.repo" #Место хранения репозитория
REPOINIT="git init" #Команда инициализации репозитория
ADDCMD="git add" #Команда на добавление файла в репозиторий
COMMITCMD="git commit -a" #Комманда для коммита
COMMITCOMMENT="-m" #Добавление комментария к коммиту
PUSHCMD="git push" #Выгрузка изменений в удалённый репозиторий
#---------------------

CURDIR="$PWD" #Сохраняем текущий путь для дальнейшего использования


function init_repo(){
	eval "mkdir -p $REPOPATH"
	eval "touch $REPOPATH/.files"
	cd "$REPOPATH"
	eval "$REPOINIT"
	eval "$ADDCMD .files"
	eval "$COMMITCMD $COMMITCOMMENT 'Iitial commit'"
	return 0
}

function commit(){
	if test ! -z "$1"
	then
		COMMENT="$COMMITCOMMENT '$1'"
	else
		COMMENT=""
	fi
	eval "$COMMITCMD $COMMENT"
}

if test ! -d "$REPOPATH"
then
	init_repo
fi

if ! test -z "$1"
then
	ACTION="$1"
else
	echo "No Action!"
	exit 2
fi

if test ! -z "$2"
then
	TARGET="$2"
	if test ! -z "$3"
	then
		TARGET_="$3"
	else
		TARGET_=`basename "$TARGET"|sed "s/^\.//"`
	fi
else
	if test "$ACTION" == "add"
	then
		echo "No targret!"
		exit 3
	else
		TARGET=""
	fi
fi


cd "$REPOPATH"

if test "$ACTION" == "commit"
then
	commit "$TARGET"
fi

if test "$ACTION" == "push"
then
	eval "$PUSHCMD"
fi

if test "$ACTION" == "add"
then
	COMMENT="Added $CURDIR/$TARGET"

	if test -f "$REPOPATH/$TARGET_"
	then
		echo "File exists! Rename? (Blank for cancel):"
		read TARGET_
		if test -z "$TARGET_"
		then
			exit 4
		fi
	fi

	eval "mv '$CURDIR/$TARGET' '$REPOPATH/$TARGET_'"
	eval "ln -s '$REPOPATH/$TARGET_' '$CURDIR/$TARGET'"
	eval "$ADDCMD $TARGET_"
	eval "$COMMITCMD $COMMITCOMMENT '$COMMENT'"
	
	echo "$TARGET_||$CURDIR/$TARGET">>$REPOPATH/.files
fi



exit 0
