#!/bin/bash

xbindkeys&
conky &
setxkbmap -layout "us,ru" -variant ,winkeys -option "grp:caps_toggle,grp_led:caps,compose:ralt"
#mpd2gajim &
xxkb &
#gvolwheel &
volumeicon &

if $NOFEH
then
	echo "Nofeh"
else
	eval `cat ~/.fehbg`
fi

